version: "3.8"
services:
  devopsdb:
    container_name: devopsdb
    image: ashok898/mydbimage:v1
    ports:
      - "3306:3306"

  myapp:
    image: ashok898/myappimage:v1
    ports:
      - "1232:8080"
    depends_on:
      - "devopsdb"
